export const products = [
  // Electronics
  {
    id: "E1",
    category: "Electronics",
    name: "iPhone 14 Pro",
    price: 129900,
    reviews: 4,
    quantity: 10,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "E2",
    category: "Electronics",
    name: "Samsung Galaxy S23",
    price: 74999,
    reviews: 4,
    quantity: 15,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "E3",
    category: "Electronics",
    name: "Sony WH-1000XM5",
    price: 29990,
    reviews: 5,
    quantity: 20,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "E4",
    category: "Electronics",
    name: "MacBook Air M2",
    price: 114900,
    reviews: 5,
    quantity: 8,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "E5",
    category: "Electronics",
    name: "Dell XPS 15",
    price: 150000,
    reviews: 4,
    quantity: 5,
    image: "/placeholder.svg?height=400&width=400",
  },

  // Groceries
  {
    id: "G1",
    category: "Groceries",
    name: "Basmati Rice",
    price: 1200,
    reviews: 4,
    quantity: 50,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "G2",
    category: "Groceries",
    name: "Organic Turmeric",
    price: 500,
    reviews: 5,
    quantity: 100,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "G3",
    category: "Groceries",
    name: "Cold Pressed Mustard Oil",
    price: 300,
    reviews: 4,
    quantity: 75,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "G4",
    category: "Groceries",
    name: "Whole Wheat Atta",
    price: 250,
    reviews: 4,
    quantity: 80,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "G5",
    category: "Groceries",
    name: "Himalayan Pink Salt",
    price: 150,
    reviews: 5,
    quantity: 120,
    image: "/placeholder.svg?height=400&width=400",
  },

  // Home Appliances
  {
    id: "H1",
    category: "Home Appliances",
    name: "LG Smart TV",
    price: 55000,
    reviews: 4,
    quantity: 10,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "H2",
    category: "Home Appliances",
    name: "Dyson Vacuum Cleaner",
    price: 40000,
    reviews: 5,
    quantity: 15,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "H3",
    category: "Home Appliances",
    name: "Philips Air Fryer",
    price: 15000,
    reviews: 4,
    quantity: 20,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "H4",
    category: "Home Appliances",
    name: "Bosch Washing Machine",
    price: 35000,
    reviews: 4,
    quantity: 12,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "H5",
    category: "Home Appliances",
    name: "Prestige Induction Cooktop",
    price: 3000,
    reviews: 4,
    quantity: 30,
    image: "/placeholder.svg?height=400&width=400",
  },

  // Fashion
  {
    id: "F1",
    category: "Fashion",
    name: "Nike Running Shoes",
    price: 7500,
    reviews: 5,
    quantity: 25,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "F2",
    category: "Fashion",
    name: "Levi's Jeans",
    price: 3500,
    reviews: 4,
    quantity: 40,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "F3",
    category: "Fashion",
    name: "Ray-Ban Sunglasses",
    price: 6000,
    reviews: 5,
    quantity: 20,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "F4",
    category: "Fashion",
    name: "Titan Watch",
    price: 9000,
    reviews: 4,
    quantity: 15,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "F5",
    category: "Fashion",
    name: "Adidas Hoodie",
    price: 4500,
    reviews: 4,
    quantity: 30,
    image: "/placeholder.svg?height=400&width=400",
  },

  // Books
  {
    id: "B1",
    category: "Books",
    name: "The Alchemist",
    price: 400,
    reviews: 5,
    quantity: 50,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "B2",
    category: "Books",
    name: "Atomic Habits",
    price: 500,
    reviews: 5,
    quantity: 45,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "B3",
    category: "Books",
    name: "Rich Dad Poor Dad",
    price: 450,
    reviews: 4,
    quantity: 40,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "B4",
    category: "Books",
    name: "Sapiens",
    price: 700,
    reviews: 5,
    quantity: 35,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: "B5",
    category: "Books",
    name: "The Psychology of Money",
    price: 550,
    reviews: 4,
    quantity: 38,
    image: "/placeholder.svg?height=400&width=400",
  },
] as const

export const categories = ["Electronics", "Groceries", "Home Appliances", "Fashion", "Books"] as const

